# Generated by Django 5.2.13 on 2026-04-23 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmé'), ('cancelled', 'Annulé'), ('completed', 'Terminé')], default='pending', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'appointments',
                'ordering': ['date', 'time'],
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mileage', models.IntegerField()),
                ('fuel', models.CharField(choices=[('Essence', 'Essence'), ('Diesel', 'Diesel'), ('Hybride', 'Hybride'), ('Électrique', 'Électrique')], max_length=20)),
                ('transmission', models.CharField(choices=[('Automatique', 'Automatique'), ('Manuelle', 'Manuelle')], max_length=20)),
                ('power', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=100)),
                ('doors', models.IntegerField(default=4)),
                ('seats', models.IntegerField(default=5)),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('features', models.JSONField(default=list)),
                ('tags', models.JSONField(default=list)),
                ('badge', models.CharField(blank=True, max_length=50)),
                ('gradient', models.CharField(blank=True, max_length=200)),
                ('accent_color', models.CharField(blank=True, max_length=10)),
                ('image', models.URLField(blank=True, max_length=500)),
                ('image_hero', models.URLField(blank=True, max_length=500)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cars',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'favorites',
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('seller_type', models.CharField(choices=[('pro', 'Professionnel'), ('particulier', 'Particulier')], default='pro', max_length=20)),
                ('avatar', models.CharField(max_length=5)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('review_count', models.IntegerField(default=0)),
                ('location', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sellers',
            },
        ),
    ]
