# Generated by Django 4.2.30 on 2026-05-01 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0003_add_car_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('fake', 'Annonce frauduleuse'), ('wrong_price', 'Prix trompeur'), ('not_responding', 'Vendeur ne répond pas'), ('not_serious', 'Vendeur pas sérieux'), ('already_sold', 'Véhicule déjà vendu'), ('harassment', 'Comportement inapproprié'), ('other', 'Autre raison')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('resolved', 'Résolu'), ('dismissed', 'Rejeté')], default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True)),
                ('admin_action', models.CharField(blank=True, choices=[('', 'Aucune'), ('warn', 'Avertissement envoyé'), ('suspend_car', 'Annonce suspendue'), ('suspend_user', 'Compte suspendu'), ('ban_user', 'Compte banni')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='cars.car')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_sent', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to='cars.seller')),
            ],
            options={
                'db_table': 'reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
