# Generated by Django 4.2.30 on 2026-05-01 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_add_report_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seller',
            name='premium_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seller',
            name='premium_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
