# Generated by Django 4.2.30 on 2026-04-30 20:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_card_number',
            field=models.CharField(max_length=13, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Le numero de CNI doit contenir exactement 13 chiffres.', regex='^\\d{13}$')], verbose_name='Numero CNI'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Numero de telephone senegalais invalide (ex: +221 77 123 45 67).', regex='^(\\+?221)?\\s?(7[05678])\\s?\\d{3}\\s?\\d{2}\\s?\\d{2}$')]),
        ),
    ]
