# Generated by Django 4.2.30 on 2026-04-30 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_id_card_number_and_phone_validator'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_image',
            field=models.FileField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
